name: Backup Satisfactory Saves
on: 
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - main
jobs:
  copy-files-from-server:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory
        run: mkdir ~/.ssh
      - name: Install SSH Key
        run: echo "${{secrets.SATISFACTORY_PRIVATE_KEY}}" > ~/.ssh/id_rsa
      - name: Add Host key
        run: ssh-keyscan -H ${{ secrets.SATISFACTORY_HOST }} >> ~/.ssh/known_hosts
      - name: Correct SSH key file permissions
        run: chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
      - name: Copy Save Files
        run: rsync -e "ssh -i ~/.ssh/id_rsa" -a github-backups@${{secrets.SATISFACTORY_HOST}}:/home/satisfactory/config/saves /tmp/satisfactory
      - name: Save File SHA256 Hashes
        run: sha256sum /tmp/satisfactory/saves/* > /tmp/satisfactory/save_hashes.txt
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Satisfactory-save-files
          path: /tmp/satisfactory


