name: Backup Satisfacotory Saves
on: 
  schedule:
    - cron: '5 * * * *'
jobs:
  copy-files-from-server:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SATISFACTORY_PRIVATE_KEY}}}
          known_hosts: ${{secrets.SATISFACTORY_HOST_SIG}}}
          name: id_rsa
      - name: Copy Save Files
        run: rsync -e "ssh -i ~/.ssh/id_rsa" -a github-backups@{{secrets.SATISFACTORY_HOST}}:/home/satisfactory/config/saves /tmp/satisfactory
      - name: Save File SHA256 Hashes
        run: sha256sum /tmp/satisfactory/* > /tmp/satisfactory/save_hashes.txt
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Satisfactory-save-files
          path: /tmp/satisfactory


